<?php

namespace Container2axRe0u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CgWhreGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cgWhreG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cgWhreG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PropertiesController::delete' => ['privates', '.service_locator.rY0133r', 'get_ServiceLocator_RY0133rService', true],
            'App\\Controller\\PropertiesController::deletePicture' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\PropertiesController::formProperty' => ['privates', '.service_locator..64EzdY', 'get_ServiceLocator__64EzdYService', true],
            'App\\Controller\\PropertiesController::picturesAdd' => ['privates', '.service_locator.rY0133r', 'get_ServiceLocator_RY0133rService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\PropertiesController:delete' => ['privates', '.service_locator.rY0133r', 'get_ServiceLocator_RY0133rService', true],
            'App\\Controller\\PropertiesController:deletePicture' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\PropertiesController:formProperty' => ['privates', '.service_locator..64EzdY', 'get_ServiceLocator__64EzdYService', true],
            'App\\Controller\\PropertiesController:picturesAdd' => ['privates', '.service_locator.rY0133r', 'get_ServiceLocator_RY0133rService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\PropertiesController::delete' => '?',
            'App\\Controller\\PropertiesController::deletePicture' => '?',
            'App\\Controller\\PropertiesController::formProperty' => '?',
            'App\\Controller\\PropertiesController::picturesAdd' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PropertiesController:delete' => '?',
            'App\\Controller\\PropertiesController:deletePicture' => '?',
            'App\\Controller\\PropertiesController:formProperty' => '?',
            'App\\Controller\\PropertiesController:picturesAdd' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
