<?php

namespace ContainerC90PFtf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RY0133rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rY0133r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rY0133r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'property' => ['privates', '.errored..service_locator.rY0133r.App\\Entity\\Properties', NULL, 'Cannot autowire service ".service_locator.rY0133r": it references class "App\\Entity\\Properties" but no such service exists.'],
        ], [
            'manager' => '?',
            'property' => 'App\\Entity\\Properties',
        ]);
    }
}
