<?php

namespace ContainerC90PFtf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertiesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.p7s7Hn6.App\Entity\Properties' shared service.
     *
     * @return \App\Entity\Properties
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.p7s7Hn6": it references class "App\\Entity\\Properties" but no such service exists.');
    }
}
